# Generated by Django 6.0.7 on 2026-07-23 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '__first__'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoOrden',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ESTADO_ORDEN',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HerraOrden',
            fields=[
                ('herramienta', models.OneToOneField(db_column='herramienta', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='inventario.herramienta')),
            ],
            options={
                'db_table': 'HERRA_ORDEN',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('numeroregistro', models.AutoField(db_column='numeroRegistro', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('tipomovimiento', models.CharField(db_column='tipoMovimiento', max_length=20)),
            ],
            options={
                'db_table': 'MOVIMIENTO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenMantenimiento',
            fields=[
                ('folio', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=500)),
                ('diagnostico', models.CharField(blank=True, max_length=500, null=True)),
                ('notas', models.CharField(blank=True, max_length=500, null=True)),
                ('fechaprogramada', models.DateField(blank=True, db_column='fechaProgramada', null=True)),
                ('fechacreacion', models.DateField(db_column='fechaCreacion')),
                ('horacreacion', models.TimeField(db_column='horaCreacion')),
                ('fechacierre', models.DateField(blank=True, db_column='fechaCierre', null=True)),
                ('horacierre', models.TimeField(blank=True, db_column='horaCierre', null=True)),
                ('horasintervenidas', models.FloatField(blank=True, db_column='horasIntervenidas', null=True)),
                ('porcentaje', models.FloatField(blank=True, null=True)),
                ('imagen', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ORDEN_MANTENIMIENTO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('numeroregistro', models.AutoField(db_column='numeroRegistro', primary_key=True, serialize=False)),
                ('instruccion', models.CharField(max_length=100)),
                ('actividad', models.IntegerField()),
            ],
            options={
                'db_table': 'TAREAS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoMantenimiento',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'TIPO_MANTENIMIENTO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoMovimiento',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'TIPO_MOVIMIENTO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrabaOrdePersonal',
            fields=[
                ('trabajador', models.OneToOneField(db_column='trabajador', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='usuarios.trabajador')),
            ],
            options={
                'db_table': 'TRABA_ORDE_PERSONAL',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TareaOrden',
            fields=[
                ('tarea', models.OneToOneField(db_column='tarea', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='mantenimiento.tareas')),
                ('fechainicio', models.DateField(db_column='fechaInicio')),
                ('fechacierre', models.DateField(blank=True, db_column='fechaCierre', null=True)),
                ('horainicio', models.TimeField(db_column='horaInicio')),
                ('horafin', models.TimeField(blank=True, null=True)),
                ('verificacion', models.IntegerField(blank=True, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'TAREA_ORDEN',
                'managed': False,
            },
        ),
    ]
