# Generated by Django 4.2.17 on 2026-07-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoReporte',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'EDO_REPORTE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('numeroSerie', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('imagen_url', models.CharField(blank=True, max_length=255, null=True)),
                ('fechaInstalacion', models.DateField()),
                ('linea', models.CharField(blank=True, max_length=10, null=True)),
                ('marca', models.CharField(blank=True, max_length=10, null=True)),
                ('modelo', models.CharField(blank=True, max_length=10, null=True)),
                ('estado_maquina', models.CharField(blank=True, max_length=5, null=True)),
                ('tipo_maquina', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'MAQUINA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReporteFalla',
            fields=[
                ('numeroRegistro', models.AutoField(primary_key=True, serialize=False)),
                ('asunto', models.CharField(max_length=500)),
                ('fechaResolucion', models.DateField()),
                ('fechaCreacion', models.DateField()),
                ('horaCreacion', models.TimeField()),
                ('tiempoParo', models.IntegerField(blank=True, null=True)),
                ('causaRaiz', models.CharField(max_length=500)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('imagen', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'REPORTE_FALLA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoFalla',
            fields=[
                ('numeroRegistro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'TIPO_FALLA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoReporte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'TIPO_REPORTE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoSeveridad',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'TIPO_SEVERIDAD',
                'managed': False,
            },
        ),
    ]
