# Generated by Django 6.0.7 on 2026-07-23 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fallas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoMaquina',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'EDO_MAQUINA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'LINEA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('clave', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'MARCA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'MODELO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoMaquina',
            fields=[
                ('numeroRegistro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'TIPO_MAQUINA',
                'managed': False,
            },
        ),
    ]
