# Generated by Django 4.2 on 2026-07-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fallas', '0002_estadomaquina_linea_marca_modelo_tipomaquina'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMaquinaArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(db_column='area', max_length=10)),
            ],
            options={
                'db_table': 'TIPO_MAQUINA_AREA',
                'managed': False,
            },
        ),
    ]
