# Generated by Django 6.0.7 on 2026-07-17 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'CLASIFICACION',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EdoHerramienta',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'EDO_HERRAMIENTA',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EdoRefaccion',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'EDO_REFACCION',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('rfc', models.CharField(max_length=13, unique=True)),
                ('razon_social', models.CharField(db_column='razonSocial', max_length=100, unique=True)),
                ('nombre_comercial', models.CharField(db_column='nombreComercial', max_length=100, unique=True)),
                ('telefono', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('dir_calle', models.CharField(db_column='dirCalle', max_length=100)),
                ('dir_codigo_postal', models.CharField(db_column='dirCodigoPostal', max_length=5)),
                ('dir_numero', models.CharField(db_column='dirNumero', max_length=10)),
                ('cont_nombre', models.CharField(db_column='contNombre', max_length=50)),
                ('cont_apell_pat', models.CharField(db_column='contApellPat', max_length=50)),
                ('cont_apell_mat', models.CharField(blank=True, db_column='contApellMat', max_length=50, null=True)),
            ],
            options={
                'db_table': 'PROVEEDOR',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoHerramienta',
            fields=[
                ('numero_registro', models.AutoField(db_column='numeroRegistro', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'TIPO_HERRAMIENTA',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoRefaccion',
            fields=[
                ('numero_registro', models.AutoField(db_column='numeroRegistro', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'TIPO_REFACCION',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Refaccion',
            fields=[
                ('numero_registro', models.AutoField(db_column='numeroRegistro', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('codigo_sku', models.CharField(db_column='codigoSku', max_length=30, unique=True)),
                ('punto_reorden', models.IntegerField(blank=True, db_column='puntoReorden', null=True)),
                ('codigo_inventario', models.CharField(db_column='codigoInventario', max_length=30, unique=True)),
                ('numero_orden', models.CharField(db_column='numeroOrden', max_length=20, unique=True)),
                ('costo', models.FloatField()),
                ('tiempo_entrega_apr', models.IntegerField(blank=True, db_column='tiempoEntregaApr', null=True)),
                ('stock', models.IntegerField(default=0)),
                ('stock_minimo', models.IntegerField(db_column='stockMinimo', default=0)),
                ('clasificacion', models.ForeignKey(blank=True, db_column='clasificacion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refacciones', to='inventario.clasificacion')),
                ('proveedor', models.ForeignKey(blank=True, db_column='proveedor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refacciones', to='inventario.proveedor')),
                ('tipo_refaccion', models.ForeignKey(blank=True, db_column='tipo_refaccion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refacciones', to='inventario.tiporefaccion')),
            ],
            options={
                'db_table': 'REFACCION',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('numero_registro', models.AutoField(db_column='numeroRegistro', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], db_column='tipoMovimiento', max_length=20)),
                ('orden_mantenimiento', models.IntegerField(blank=True, db_column='orden_mantenimiento', null=True)),
                ('refaccion', models.ForeignKey(blank=True, db_column='refaccion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='inventario.refaccion')),
            ],
            options={
                'db_table': 'MOVIMIENTO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('numero_registro', models.AutoField(db_column='numeroRegistro', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('imagen', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_herramienta', models.ForeignKey(blank=True, db_column='tipo_herramienta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='herramientas', to='inventario.tipoherramienta')),
            ],
            options={
                'db_table': 'HERRAMIENTA',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EstadoHerramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('edo_herramienta', models.ForeignKey(db_column='edo_herramienta', on_delete=django.db.models.deletion.CASCADE, to='inventario.edoherramienta')),
                ('herramienta', models.ForeignKey(db_column='herramienta', on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='inventario.herramienta')),
            ],
            options={
                'db_table': 'ESTADO_HERRAMIENTA',
                'managed': True,
                'unique_together': {('herramienta', 'edo_herramienta')},
            },
        ),
        migrations.CreateModel(
            name='EstadoRefaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('estado_refaccion', models.ForeignKey(db_column='estado_refaccion', on_delete=django.db.models.deletion.CASCADE, to='inventario.edorefaccion')),
                ('refaccion', models.ForeignKey(db_column='refaccion', on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='inventario.refaccion')),
            ],
            options={
                'db_table': 'ESTADO_REFACCION',
                'managed': True,
                'unique_together': {('estado_refaccion', 'refaccion')},
            },
        ),
    ]
