# Generated by Django 4.2 on 2026-07-23 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maquinaria', '0002_area_edomaquina_linea_marca_modelo_planta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'CLASIFICACION',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EdoHerramienta',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'EDO_HERRAMIENTA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EdoPieza',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'EDO_PIEZA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EdoRefaccion',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'EDO_REFACCION',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('numeroregistro', models.AutoField(db_column='numeroRegistro', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('imagen', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'HERRAMIENTA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pieza',
            fields=[
                ('numeroserie', models.CharField(db_column='numeroSerie', max_length=30, primary_key=True, serialize=False)),
                ('codigoetiqueta', models.CharField(blank=True, db_column='codigoEtiqueta', max_length=30, null=True, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('costoinicial', models.FloatField(db_column='costoInicial')),
                ('horasoperacion', models.IntegerField(db_column='horasOperacion')),
                ('tiempovidautil', models.IntegerField(db_column='tiempoVidaUtil')),
                ('depresacionanual', models.FloatField(blank=True, db_column='depresacionAnual', null=True)),
                ('valorresidual', models.FloatField(blank=True, db_column='valorResidual', null=True)),
                ('fechainstalacion', models.DateField(db_column='fechaInstalacion')),
                ('fechagarantia', models.DateField(blank=True, db_column='fechaGarantia', null=True)),
            ],
            options={
                'db_table': 'PIEZA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('rfc', models.CharField(max_length=13, unique=True)),
                ('razonsocial', models.CharField(db_column='razonSocial', max_length=100, unique=True)),
                ('nombrecomercial', models.CharField(db_column='nombreComercial', max_length=100, unique=True)),
                ('telefono', models.CharField(max_length=15, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('dircalle', models.CharField(db_column='dirCalle', max_length=100)),
                ('dircodigopostal', models.CharField(db_column='dirCodigoPostal', max_length=5)),
                ('dirnumero', models.CharField(db_column='dirNumero', max_length=10)),
                ('contnombre', models.CharField(db_column='contNombre', max_length=50)),
                ('contapellpat', models.CharField(db_column='contApellPat', max_length=50)),
                ('contapellmat', models.CharField(blank=True, db_column='contApellMat', max_length=50, null=True)),
            ],
            options={
                'db_table': 'PROVEEDOR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Refaccion',
            fields=[
                ('numeroregistro', models.AutoField(db_column='numeroRegistro', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('codigosku', models.CharField(db_column='codigoSku', max_length=30, unique=True)),
                ('puntoreorden', models.IntegerField(blank=True, db_column='puntoReorden', null=True)),
                ('codigoinventario', models.CharField(db_column='codigoInventario', max_length=30, unique=True)),
                ('numeroorden', models.CharField(db_column='numeroOrden', max_length=20, unique=True)),
                ('costo', models.FloatField()),
                ('tiempoentregaapr', models.IntegerField(blank=True, db_column='tiempoEntregaApr', null=True)),
                ('stock', models.IntegerField()),
                ('stockminimo', models.IntegerField(db_column='stockMinimo')),
            ],
            options={
                'db_table': 'REFACCION',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RefaccMaqui',
            fields=[
                ('maquina', models.OneToOneField(db_column='maquina', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='maquinaria.maquina')),
            ],
            options={
                'db_table': 'REFACC_MAQUI',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoHerramienta',
            fields=[
                ('numeroregistro', models.AutoField(db_column='numeroRegistro', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'TIPO_HERRAMIENTA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoPieza',
            fields=[
                ('numeroregistro', models.AutoField(db_column='numeroRegistro', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'TIPO_PIEZA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoRefaccion',
            fields=[
                ('numeroregistro', models.AutoField(db_column='numeroRegistro', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'TIPO_REFACCION',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoHerramienta',
            fields=[
                ('herramienta', models.OneToOneField(db_column='herramienta', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='inventario.herramienta')),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'ESTADO_HERRAMIENTA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoRefaccion',
            fields=[
                ('estado_refaccion', models.OneToOneField(db_column='estado_refaccion', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='inventario.edorefaccion')),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'ESTADO_REFACCION',
                'managed': False,
            },
        ),
    ]
