# Generated by Django 4.2 on 2026-07-21 05:05
# Generated by Django 4.2.17 on 2026-07-17 20:28


from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ESPECIALIDAD',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ROL',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('numeroNomina', models.CharField(db_column='numeroNomina', max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidoPat', models.CharField(db_column='apellidoPat', max_length=50)),
                ('apellidoMat', models.CharField(blank=True, db_column='apellidoMat', max_length=50, null=True)),
                ('telefono', models.CharField(max_length=15, unique=True)),
                ('correo', models.CharField(max_length=100, unique=True)),
                ('usuario', models.CharField(max_length=30, unique=True)),
                ('contrasena', models.CharField(db_column='contraseña', max_length=255)),
                ('actividad', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'TRABAJADOR',
                'managed': False,
            },
        ),
    ]
