# Generated by Django 4.2.17 on 2026-07-17 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoMaquina',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'EDO_MAQUINA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoPieza',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'EDO_PIEZA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('numeroRegistro', models.AutoField(primary_key=True, serialize=False)),
                ('fechaInicio', models.DateField(blank=True, null=True)),
                ('fechaFin', models.DateField(blank=True, null=True)),
                ('mttr', models.FloatField(blank=True, null=True)),
                ('mtbf', models.FloatField(blank=True, null=True)),
                ('porcentajeDispo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'INDICADOR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('numeroSerie', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('imagen_url', models.CharField(blank=True, max_length=255, null=True)),
                ('modelo_3d', models.CharField(blank=True, max_length=255, null=True)),
                ('fechaInstalacion', models.DateField()),
                ('linea', models.CharField(blank=True, max_length=10, null=True)),
                ('marca', models.CharField(blank=True, max_length=10, null=True)),
                ('modelo', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'MAQUINA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenMantenimiento',
            fields=[
                ('folio', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=500)),
                ('diagnostico', models.CharField(blank=True, max_length=500, null=True)),
                ('notas', models.CharField(blank=True, max_length=500, null=True)),
                ('fechaProgramada', models.DateField()),
                ('fechaCreacion', models.DateField()),
                ('horaCreacion', models.TimeField()),
                ('fechaCierre', models.DateField(blank=True, null=True)),
                ('horaCierre', models.TimeField(blank=True, null=True)),
                ('horasIntervenidas', models.FloatField(blank=True, null=True)),
                ('imagen', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_mantenimiento', models.CharField(blank=True, max_length=5, null=True)),
                ('estado_orden', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'ORDEN_MANTENIMIENTO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pieza',
            fields=[
                ('numeroSerie', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('codigoEtiqueta', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('costoInicial', models.FloatField()),
                ('horasOperacion', models.IntegerField(default=0)),
                ('tiempoVidaUtil', models.IntegerField()),
                ('depresacionAnual', models.FloatField(blank=True, null=True)),
                ('valorResidual', models.FloatField(blank=True, null=True)),
                ('fechaInstalacion', models.DateField()),
                ('fechaGarantia', models.DateField(blank=True, null=True)),
                ('tipo_pieza', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'PIEZA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Refaccion',
            fields=[
                ('numeroRegistro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('codigoSku', models.CharField(max_length=30, unique=True)),
                ('puntoReorden', models.IntegerField(blank=True, null=True)),
                ('codigoInventario', models.CharField(max_length=30, unique=True)),
                ('numeroOrden', models.CharField(max_length=20, unique=True)),
                ('costo', models.FloatField()),
                ('tiempoEntregaApr', models.IntegerField(blank=True, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('stockMinimo', models.IntegerField(default=0)),
                ('proveedor', models.CharField(blank=True, max_length=10, null=True)),
                ('tipo_refaccion', models.IntegerField(blank=True, null=True)),
                ('clasificacion', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'REFACCION',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RefaccMaqui',
            fields=[
                ('numeroRegistro', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'REFACC_MAQUI',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReporteFalla',
            fields=[
                ('numeroRegistro', models.AutoField(primary_key=True, serialize=False)),
                ('asunto', models.CharField(max_length=500)),
                ('fechaResolucion', models.DateField()),
                ('fechaCreacion', models.DateField()),
                ('horaCreacion', models.TimeField()),
                ('tiempoParo', models.IntegerField(blank=True, null=True)),
                ('causaRaiz', models.CharField(max_length=500)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('imagen', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_falla', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'REPORTE_FALLA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoMaquina',
            fields=[
                ('numeroRegistro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'TIPO_MAQUINA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoSeveridad',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'TIPO_SEVERIDAD',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('numeroNomina', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidoPat', models.CharField(max_length=50)),
                ('apellidoMat', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(max_length=15, unique=True)),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('usuario', models.CharField(max_length=30, unique=True)),
                ('contraseña', models.CharField(db_column='contraseña', max_length=255)),
                ('actividad', models.BooleanField(default=True)),
                ('rol', models.CharField(blank=True, max_length=5, null=True)),
                ('especialidad', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'TRABAJADOR',
                'managed': False,
            },
        ),
    ]
