# Generated by Django 6.0.7 on 2026-07-23 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinaria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'db_table': 'AREA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EdoMaquina',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'EDO_MAQUINA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'LINEA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('clave', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'MARCA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'MODELO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(max_length=15, unique=True)),
                ('dircalle', models.CharField(db_column='dirCalle', max_length=100)),
                ('dircodigopostal', models.CharField(db_column='dirCodigoPostal', max_length=5)),
                ('dirnumero', models.CharField(db_column='dirNumero', max_length=10)),
            ],
            options={
                'db_table': 'PLANTA',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='EstadoMaquina',
        ),
        migrations.DeleteModel(
            name='EstadoPieza',
        ),
        migrations.DeleteModel(
            name='Indicador',
        ),
        migrations.DeleteModel(
            name='OrdenMantenimiento',
        ),
        migrations.DeleteModel(
            name='Pieza',
        ),
        migrations.DeleteModel(
            name='Refaccion',
        ),
        migrations.DeleteModel(
            name='RefaccMaqui',
        ),
        migrations.DeleteModel(
            name='ReporteFalla',
        ),
        migrations.DeleteModel(
            name='TipoSeveridad',
        ),
        migrations.DeleteModel(
            name='Trabajador',
        ),
    ]
