# Generated by Django 4.2 on 2026-07-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinaria', '0002_area_edomaquina_linea_marca_modelo_planta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMaquinaArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'TIPO_MAQUINA_AREA',
                'managed': False,
            },
        ),
    ]
