# Generated by Django 4.2 on 2026-07-27 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinaria', '0003_tipomaquinaarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialEstadoMaquina',
            fields=[
                ('numeroregistro', models.AutoField(db_column='numeroRegistro', primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('referencia_tipo', models.CharField(blank=True, max_length=20, null=True)),
                ('referencia_id', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'HISTORIAL_ESTADO_MAQUINA',
                'ordering': ['-fecha'],
                'managed': False,
            },
        ),
    ]
